server:
  port: 8080
  servlet:
    session:
      timeout: 60

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hams
    driver-class-name: org.mariadb.jdbc.Driver
    username: huneth
    password: 1234

